parent=base
import=common/keycloak

styles=css/login.css

# Wir bringen Logo + Brand-Text selbst rein und benoetigen das Keycloak-Logo nicht.
locales=de,en

meta=viewport==width=device-width,initial-scale=1
